#  .-^~^-. \/ .-^~^-. \\ `-._.-` // .-^~^-. \/ .-^~^-.
# |                                                   |
# |   ,---.          ,--.                             |
# |  '   .-'  ,--,--.|  |,-.,--.,--.,--.--. ,--,--.   |
# |  `.  `-. ' ,-.  ||     /|  ||  ||  .--'' ,-.  |   |
# |  .-'    |\ '-'  ||  \  \'  ''  '|  |   \ '-'  |   |
# |  `-----'  `--`--'`--'`--'`----' `--'    `--`--'   |
# |                 . .         . .                   |
# |               .-^~^-.     .-^~^-.                 |
# |               `-._.-'     `-._.-'                 |
# |                  |           |                    |
# |     ,--.   ,--.             ,--.     ,--.         |
# |     |   `.'   | ,---.  ,---.|  ,---. `--'         |
# |     |  |'.'|  || .-. || .--'|  .-.  |,--.         |
# |     |  |   |  |' '-' '\ `--.|  | |  ||  |         |
# |     `--'   `--' `---'  `---'`--' `--'`--'         |
# |                                                   |
#  .-^~^-. \/ .-^~^-. \\ `-._.-` // .-^~^-. \/ .-^~^-.

[colors-dark]
# Keep every cell painted with the theme background on the transparent blur plane.
alpha=0.42
alpha-mode=matching
blur=yes
background=2a2a26
foreground=fbc6c8
cursor=2a2a26 bf3533
selection-background=bf3533
selection-foreground=2a2a26

regular0=2a2a26
regular1=bf3533
regular2=8bc7c3
regular3=e98129
regular4=fbc6c8
regular5=fbc6c8
regular6=8bc7c3
regular7=fbc6c8

bright0=2a2a26
bright1=bf3533
bright2=8bc7c3
bright3=e98129
bright4=fbc6c8
bright5=bf3533
bright6=8bc7c3
bright7=fbc6c8

#   ____  __   __
#  / __ \/ /__/ /
# / /_/ / / _  / 
# \____/_/\_,_/  
#      __     __        __      
#  __ / /__  / /  ___  / /  ___ 
# / // / _ \/ _ \/ _ \/ _ \/ _ \
# \___/\___/_.__/\___/_.__/\___/

