#  .-^~^-. \/ .-^~^-. \\ `-._.-` // .-^~^-. \/ .-^~^-.
# |                                                   |
# |   ,---.          ,--.                             |
# |  '   .-'  ,--,--.|  |,-.,--.,--.,--.--. ,--,--.   |
# |  `.  `-. ' ,-.  ||     /|  ||  ||  .--'' ,-.  |   |
# |  .-'    |\ '-'  ||  \  \'  ''  '|  |   \ '-'  |   |
# |  `-----'  `--`--'`--'`--'`----' `--'    `--`--'   |
# |                 . .         . .                   |
# |               .-^~^-.     .-^~^-.                 |
# |               `-._.-'     `-._.-'                 |
# |                  |           |                    |
# |     ,--.   ,--.             ,--.     ,--.         |
# |     |   `.'   | ,---.  ,---.|  ,---. `--'         |
# |     |  |'.'|  || .-. || .--'|  .-.  |,--.         |
# |     |  |   |  |' '-' '\ `--.|  | |  ||  |         |
# |     `--'   `--' `---'  `---'`--' `--'`--'         |
# |                                                   |
#  .-^~^-. \/ .-^~^-. \\ `-._.-` // .-^~^-. \/ .-^~^-.

[colors-dark]
# Keep every cell painted with the theme background on the transparent blur plane.
alpha=0.42
alpha-mode=matching
blur=yes
background=0b0d11
foreground=f8b6ce
cursor=0b0d11 ff1493
selection-background=ff1493
selection-foreground=0b0d11

regular0=0b0d11
regular1=ff1493
regular2=ff69b4
regular3=ff85b3
regular4=ff69b4
regular5=ffffff
regular6=ff85b3
regular7=ffffff

bright0=674242
bright1=ff0000
bright2=ff1493
bright3=ff85b3
bright4=ff69b4
bright5=ff85b3
bright6=ff69b4
bright7=ffffff

#   ____  __   __
#  / __ \/ /__/ /
# / /_/ / / _  / 
# \____/_/\_,_/  
#      __     __        __      
#  __ / /__  / /  ___  / /  ___ 
# / // / _ \/ _ \/ _ \/ _ \/ _ \
# \___/\___/_.__/\___/_.__/\___/

