#  .-^~^-. \/ .-^~^-. \\ `-._.-` // .-^~^-. \/ .-^~^-.
# |                                                   |
# |   ,---.          ,--.                             |
# |  '   .-'  ,--,--.|  |,-.,--.,--.,--.--. ,--,--.   |
# |  `.  `-. ' ,-.  ||     /|  ||  ||  .--'' ,-.  |   |
# |  .-'    |\ '-'  ||  \  \'  ''  '|  |   \ '-'  |   |
# |  `-----'  `--`--'`--'`--'`----' `--'    `--`--'   |
# |                 . .         . .                   |
# |               .-^~^-.     .-^~^-.                 |
# |               `-._.-'     `-._.-'                 |
# |                  |           |                    |
# |     ,--.   ,--.             ,--.     ,--.         |
# |     |   `.'   | ,---.  ,---.|  ,---. `--'         |
# |     |  |'.'|  || .-. || .--'|  .-.  |,--.         |
# |     |  |   |  |' '-' '\ `--.|  | |  ||  |         |
# |     `--'   `--' `---'  `---'`--' `--'`--'         |
# |                                                   |
#  .-^~^-. \/ .-^~^-. \\ `-._.-` // .-^~^-. \/ .-^~^-.

# ghostty.conf
# By OldJobobo (https://github.com/OldJobobo)
# 


# Background and foreground colors
background = #0b0d11
foreground = #ffffff
background-opacity = 0.42
cursor-color = #ff1493
selection-background = #ff1493
selection-foreground = #0b0d11

# Standard colors
palette = 0=#0b0d11
palette = 1=#ff1493
palette = 2=#ff69b4
palette = 3=#ff85b3
palette = 4=#ff69b4
palette = 5=#ffffff
palette = 6=#ff85b3
palette = 7=#ffffff

# Bright colors
palette = 8=#674242
palette = 9=#ff0000
palette = 10=#ff1493
palette = 11=#ff85b3
palette = 12=#ff69b4
palette = 13=#ff69b4
palette = 14=#ff85b3
palette = 15=#ffffff

#   ____  __   __
#  / __ \/ /__/ /
# / /_/ / / _  / 
# \____/_/\_,_/  
#      __     __        __      
#  __ / /__  / /  ___  / /  ___ 
# / // / _ \/ _ \/ _ \/ _ \/ _ \
# \___/\___/_.__/\___/_.__/\___/

#   ____  __   __
#  / __ \/ /__/ /
# / /_/ / / _  / 
# \____/_/\_,_/  
#      __     __        __      
#  __ / /__  / /  ___  / /  ___ 
# / // / _ \/ _ \/ _ \/ _ \/ _ \
# \___/\___/_.__/\___/_.__/\___/
#                               