#  .-^~^-. \/ .-^~^-. \\ `-._.-` // .-^~^-. \/ .-^~^-.
# |                                                   |
# |   ,---.          ,--.                             |
# |  '   .-'  ,--,--.|  |,-.,--.,--.,--.--. ,--,--.   |
# |  `.  `-. ' ,-.  ||     /|  ||  ||  .--'' ,-.  |   |
# |  .-'    |\ '-'  ||  \  \'  ''  '|  |   \ '-'  |   |
# |  `-----'  `--`--'`--'`--'`----' `--'    `--`--'   |
# |                 . .         . .                   |
# |               .-^~^-.     .-^~^-.                 |
# |               `-._.-'     `-._.-'                 |
# |                  |           |                    |
# |     ,--.   ,--.             ,--.     ,--.         |
# |     |   `.'   | ,---.  ,---.|  ,---. `--'         |
# |     |  |'.'|  || .-. || .--'|  .-.  |,--.         |
# |     |  |   |  |' '-' '\ `--.|  | |  ||  |         |
# |     `--'   `--' `---'  `---'`--' `--'`--'         |
# |                                                   |
#  .-^~^-. \/ .-^~^-. \\ `-._.-` // .-^~^-. \/ .-^~^-.

# kitty.conf
# By OldJobobo (https://github.com/OldJobobo)
# 

background            #2a2a26
foreground            #fbc6c8
background_opacity    0.42
background_blur 1

selection_foreground  #2a2a26
selection_background  #bf3533
cursor                #bf3533
cursor_text_color     #2a2a26
active_border_color   #bf3533
active_tab_background #bf3533

# black
color0  #2a2a26
color8  #2a2a26

# red
color1  #bf3533
color9  #bf3533

# green
color2  #8bc7c3
color10 #8bc7c3

# yellow
color3  #e98129
color11 #e98129

# blue
color4  #8bc7c3
color12 #8bc7c3

# magenta
color5  #fbc6c8
color13 #bf3533

#cyan
color6  #8bc7c3
color14 #8bc7c3

#white
color7  #fbc6c8
color15 #fbc6c8

#   ____  __   __
#  / __ \/ /__/ /
# / /_/ / / _  / 
# \____/_/\_,_/  
#      __     __        __      
#  __ / /__  / /  ___  / /  ___ 
# / // / _ \/ _ \/ _ \/ _ \/ _ \
# \___/\___/_.__/\___/_.__/\___/

#   ____  __   __
#  / __ \/ /__/ /
# / /_/ / / _  / 
# \____/_/\_,_/  
#      __     __        __      
#  __ / /__  / /  ___  / /  ___ 
# / // / _ \/ _ \/ _ \/ _ \/ _ \
# \___/\___/_.__/\___/_.__/\___/
#                               