#  .-^~^-. \/ .-^~^-. \\ `-._.-` // .-^~^-. \/ .-^~^-.
# |                                                   |
# |   ,---.          ,--.                             |
# |  '   .-'  ,--,--.|  |,-.,--.,--.,--.--. ,--,--.   |
# |  `.  `-. ' ,-.  ||     /|  ||  ||  .--'' ,-.  |   |
# |  .-'    |\ '-'  ||  \  \'  ''  '|  |   \ '-'  |   |
# |  `-----'  `--`--'`--'`--'`----' `--'    `--`--'   |
# |                 . .         . .                   |
# |               .-^~^-.     .-^~^-.                 |
# |               `-._.-'     `-._.-'                 |
# |                  |           |                    |
# |     ,--.   ,--.             ,--.     ,--.         |
# |     |   `.'   | ,---.  ,---.|  ,---. `--'         |
# |     |  |'.'|  || .-. || .--'|  .-.  |,--.         |
# |     |  |   |  |' '-' '\ `--.|  | |  ||  |         |
# |     `--'   `--' `---'  `---'`--' `--'`--'         |
# |                                                   |
#  .-^~^-. \/ .-^~^-. \\ `-._.-` // .-^~^-. \/ .-^~^-.

# kitty.conf
# By OldJobobo (https://github.com/OldJobobo)
# 

background            #0b0d11
foreground            #ffffff
background_opacity    0.42
background_blur 1

selection_foreground  #0b0d11
selection_background  #ff69b4
cursor                #ff69b4
cursor_text_color     #0b0d11
active_border_color   #ff69b4
active_tab_background #ff69b4

# black
color0  #0b0d11
color8  #674242

# red
color1  #ff69b4
color9  #ff0000

# green
color2  #ff1493
color10 #ff69b4

# yellow
color3  #ffb6c1
color11 #ffb6c1

# blue
color4  #db7093
color12 #ff1493

# magenta
color5  #ffffff
color13 #db7093

#cyan
color6  #ffb6c1
color14 #ff85b3

#white
color7  #ffffff
color15 #ffffff

#   ____  __   __
#  / __ \/ /__/ /
# / /_/ / / _  / 
# \____/_/\_,_/  
#      __     __        __      
#  __ / /__  / /  ___  / /  ___ 
# / // / _ \/ _ \/ _ \/ _ \/ _ \
# \___/\___/_.__/\___/_.__/\___/

#   ____  __   __
#  / __ \/ /__/ /
# / /_/ / / _  / 
# \____/_/\_,_/  
#      __     __        __      
#  __ / /__  / /  ___  / /  ___ 
# / // / _ \/ _ \/ _ \/ _ \/ _ \
# \___/\___/_.__/\___/_.__/\___/
#                               