#  .-^~^-. \/ .-^~^-. \\ `-._.-` // .-^~^-. \/ .-^~^-.
# |                                                   |
# |   ,---.          ,--.                             |
# |  '   .-'  ,--,--.|  |,-.,--.,--.,--.--. ,--,--.   |
# |  `.  `-. ' ,-.  ||     /|  ||  ||  .--'' ,-.  |   |
# |  .-'    |\ '-'  ||  \  \'  ''  '|  |   \ '-'  |   |
# |  `-----'  `--`--'`--'`--'`----' `--'    `--`--'   |
# |                 . .         . .                   |
# |               .-^~^-.     .-^~^-.                 |
# |               `-._.-'     `-._.-'                 |
# |                  |           |                    |
# |     ,--.   ,--.             ,--.     ,--.         |
# |     |   `.'   | ,---.  ,---.|  ,---. `--'         |
# |     |  |'.'|  || .-. || .--'|  .-.  |,--.         |
# |     |  |   |  |' '-' '\ `--.|  | |  ||  |         |
# |     `--'   `--' `---'  `---'`--' `--'`--'         |
# |                                                   |
#  .-^~^-. \/ .-^~^-. \\ `-._.-` // .-^~^-. \/ .-^~^-.

text-color=#fbc6c8
border-color=#bf35334d
background-color=#2a2a26
width=420
height=110
padding=10
border-size=2
font=Liberation Sans 11
anchor=top-right
outer-margin=20
default-timeout=5000
max-icon-size=32

[app-name=Spotify]
invisible=1

[mode=do-not-disturb]
invisible=true

[mode=do-not-disturb app-name=notify-send]
invisible=false

#   ____  __   __
#  / __ \/ /__/ /
# / /_/ / / _  / 
# \____/_/\_,_/  
#      __     __        __      
#  __ / /__  / /  ___  / /  ___ 
# / // / _ \/ _ \/ _ \/ _ \/ _ \
# \___/\___/_.__/\___/_.__/\___/

#   ____  __   __
#  / __ \/ /__/ /
# / /_/ / / _  / 
# \____/_/\_,_/  
#      __     __        __      
#  __ / /__  / /  ___  / /  ___ 
# / // / _ \/ _ \/ _ \/ _ \/ _ \
# \___/\___/_.__/\___/_.__/\___/
#                               